#!/usr/bin/env python
"""
Reproduce EMMIA for ONE domain: AUC and TPR@5%FPR per model size.

EMMIA is a separate pipeline from the other methods (see evaluate.py). It scores
contaminated and uncontaminated JOINTLY, so it is generated by
methods/emmia_method.py (one run per domain, NOT run_all.slurm), which writes a
combined emmia_<size>.json. Per (domain, size) both metrics are the MAX over its
four submethods (loss/zlib/mink/minkpp) of the pooled contaminated-vs-uncontaminated
ROC-AUC / TPR@FPR. Precomputed EMMIA scores are not shipped; reproduce a domain
like this.

End-to-end (DCLM-Baseline, 1B; repeat the generate step for 7B/13B/32B):
  # Step 1 — generate scores (joint con+uncon) -> emmia_dclm/emmia_1b.json
  python methods/emmia_method.py \\
      --model olmo_models/OLMo2-1B-Instruct \\
      --con-eval-path   benchmark/pretraining/dclm/contaminated/matched/test/contaminated_pretraining_dclm_test_matched.jsonl \\
      --uncon-eval-path benchmark/pretraining/dclm/uncontaminated/test/uncontaminated_pretraining_dclm_test.jsonl \\
      --output emmia_dclm/emmia_1b.json \\
      --max-tokens 512 --prefix-batch-size 8 --n-iterations 10 --minkpp-k 20

  # Step 2 — score (once the sizes you want are generated)
  python evaluate_emmia.py --emmia-dir emmia_dclm

  # A domain split over several files (e.g. SFT model-pair dirs, or DPO
  # chosen+rejected) is pooled by passing the dirs together:
  #   python evaluate_emmia.py --emmia-dir emmia_dpo_1b_chosen emmia_dpo_1b_rejected
"""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve

SIZES = ["1b", "7b", "13b", "32b"]
SUB = ("loss", "zlib", "mink", "minkpp")

def metrics(dirs, size, fpr):
    """Max over submethods of the pooled con-vs-uncon AUC and TPR@fpr.
    Returns (auc, tpr), or (None, None) if there is no usable data."""
    samples = []
    for d in dirs:
        p = Path(d) / f"emmia_{size}.json"
        if p.exists():
            samples += json.loads(p.read_text()).get("samples", [])
    if not samples:
        return None, None
    y = np.array([s["label"] for s in samples])
    if len(set(y.tolist())) < 2:
        return None, None
    aucs, tprs = [], []
    for k in SUB:
        sc = np.array([s["final_scores"][k] for s in samples], dtype=float)
        aucs.append(float(roc_auc_score(y, sc)))
        if np.all(sc == sc[0]):
            tprs.append(float(fpr))
        else:
            f, t, _ = roc_curve(y, sc)
            tprs.append(float(np.interp(fpr, f, t)))
    return max(aucs), max(tprs)

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emmia-dir", nargs="+", required=True,
                    help="dir(s) of emmia_<size>.json from emmia_method.py "
                         "(pass several to pool, e.g. DPO chosen+rejected)")
    ap.add_argument("--fpr", type=float, default=0.05, help="FPR for TPR@FPR (default 0.05)")
    a = ap.parse_args()

    pct = format(a.fpr * 100, "g")
    print(f"{'size':>5}  {'AUC':>8}  {'TPR@'+pct+'%':>9}")
    aucs, tprs = [], []
    for s in SIZES:
        au, tp = metrics(a.emmia_dir, s, a.fpr)
        if au is None:
            continue
        aucs.append(au); tprs.append(tp)
        print(f"{s.upper():>5}  {au:8.4f}  {tp:9.4f}")
    if aucs:
        print(f"{'Avg':>5}  {sum(aucs)/len(aucs):8.4f}  {sum(tprs)/len(tprs):9.4f}")

if __name__ == "__main__":
    main()
