#!/usr/bin/env python
"""
Reproduce EMMIA for ONE domain: AUC per model size.

EMMIA is a separate pipeline from the other methods (see evaluate.py). It scores
contaminated and uncontaminated JOINTLY, so it is generated by
methods/emmia_method.py (one run per domain, NOT run_all.slurm), which writes a
combined emmia_<size>.json. Per (domain, size) the AUC is the MAX over its four
submethods (loss/zlib/mink/minkpp) of the pooled contaminated-vs-uncontaminated
ROC-AUC. Precomputed EMMIA scores are not shipped; reproduce a domain like this.

End-to-end (DCLM-Baseline, 1B; repeat the generate step for 7B/13B/32B):
  # Step 1 — generate scores (joint con+uncon) -> emmia_dclm/emmia_1b.json
  python methods/emmia_method.py \\
      --model olmo_models/OLMo2-1B-Instruct \\
      --con-eval-path   benchmark/pretraining/dclm/contaminated/matched/test/contaminated_pretraining_dclm_test_matched.jsonl \\
      --uncon-eval-path benchmark/pretraining/dclm/uncontaminated/test/uncontaminated_pretraining_dclm_test.jsonl \\
      --output emmia_dclm/emmia_1b.json \\
      --max-tokens 512 --prefix-batch-size 8 --n-iterations 10 --minkpp-k 20

  # Step 2 — score (once the sizes you want are generated)
  python evaluate_emmia.py --emmia-dir emmia_dclm

  # DPO pools chosen+rejected: generate both, then pass both dirs:
  #   python evaluate_emmia.py --emmia-dir emmia_dpo_1b_chosen emmia_dpo_1b_rejected
"""
from __future__ import annotations
import argparse, json
from pathlib import Path
from sklearn.metrics import roc_auc_score

SIZES = ["1b", "7b", "13b", "32b"]
SUB = ("loss", "zlib", "mink", "minkpp")

def auc(dirs, size):
    """Max over submethods of the pooled con-vs-uncon AUC; None if no data."""
    samples = []
    for d in dirs:
        p = Path(d) / f"emmia_{size}.json"
        if p.exists():
            samples += json.loads(p.read_text()).get("samples", [])
    if not samples:
        return None
    y = [s["label"] for s in samples]
    if len(set(y)) < 2:
        return None
    return max(roc_auc_score(y, [s["final_scores"][k] for s in samples]) for k in SUB)

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emmia-dir", nargs="+", required=True,
                    help="dir(s) of emmia_<size>.json from emmia_method.py "
                         "(pass several to pool, e.g. DPO chosen+rejected)")
    a = ap.parse_args()

    print(f"{'size':>5}  {'EMMIA AUC':>10}")
    vals = []
    for s in SIZES:
        v = auc(a.emmia_dir, s)
        if v is None:
            continue
        vals.append(v)
        print(f"{s.upper():>5}  {v:10.4f}")
    if vals:
        print(f"{'Avg':>5}  {sum(vals)/len(vals):10.4f}")

if __name__ == "__main__":
    main()
